<?php

namespace App\Filament\Doctor\Pages;

use Filament\Auth\Pages\Login;
use Illuminate\Contracts\Support\Htmlable;

class SignIn extends Login
{

    public function getTitle(): string|Htmlable
    {
        return __('ورود به پنل دکتر | کلینیک دامپزشکی');
    }

    public function getHeading(): string|Htmlable|null
    {
        return __('ورود به پنل دکتر');
    }

    public function getSubheading(): string|Htmlable|null
    {
        return parent::getSubheading(); // TODO: Change the autogenerated stub
    }
}
